tasks:
  - command: |
      pyenv virtualenv honeypot && pyenv activate honeypot
      pip install -U pip && pip install -r requirements.dev.in
      git clone https://github.com/nickmoreton/wagtail-honeypot.git
      cd wagtail-honeypot && git checkout wagtail-3.0 && cd ..
      echo "CSRF_TRUSTED_ORIGINS = ['https://*.gitpod.io']">> app/settings/base.py

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
